# Generated by Django 6.0.2 on 2026-02-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("timeframe", models.CharField(max_length=10)),
                ("initial_balance", models.FloatField()),
                ("spread_points", models.FloatField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("final_balance", models.FloatField()),
                ("net_profit", models.FloatField()),
                ("win_rate", models.FloatField()),
                ("max_drawdown_percent", models.FloatField()),
                ("max_drawdown_amount", models.FloatField()),
                ("total_trades", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquityPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("balance", models.FloatField()),
                ("equity", models.FloatField()),
                ("drawdown_percent", models.FloatField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_curve",
                        to="journal.backtestsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.IntegerField()),
                ("direction", models.CharField(max_length=10)),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField()),
                ("sl", models.FloatField(default=0.0)),
                ("tp", models.FloatField(default=0.0)),
                ("volume", models.FloatField()),
                ("gross_profit", models.FloatField()),
                ("net_profit", models.FloatField()),
                ("open_time", models.DateTimeField()),
                ("close_time", models.DateTimeField()),
                ("duration_minutes", models.FloatField()),
                (
                    "entry_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="journal.backtestsession",
                    ),
                ),
            ],
        ),
    ]
